let array = (Головна, Компанія, Блог, Контакти);
var valueAtIndex1 = array.getValue(1);
var valueAtIndex2 = array.getValue(2);
var valueAtIndex3 = array.getValue(3);
var valueAtIndex4 = array.getValue(4);
document.querySelector('#out1').innerHTML = valueAtIndex1;
document.querySelector('#out2').innerHTML = valueAtIndex2;
document.querySelector('#out1').innerHTML = valueAtIndex3;
document.querySelector('#out2').innerHTML = valueAtIndex4;